# Copyright 2018 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ==============================================================================

export TERM=xterm-256color
alias grep="grep --color=auto"
alias ls="ls --color=auto"

echo -e "\e[1;31m"
cat<<TF

***************************************************************************
*                                                                         *
* Welcome to Docker Cocoa!                                                *
*                                                                         *
* - The command "docker run (...)" you just typed created a container     *
*   named cocoa2025 from the image whovian-cocoa. Containers != images.   *
*                                                                         *
* - Files located on ~/host are saved on the host computer (safer)        *
* - Files outside ~/host are lost if you delete the container             *
*                                                                         *
* - How do you restart the container? "docker start -ai cocoa2025"        *
*                                                                         *
* - How do you delete the container and lose all work and data not        *
*   copied to the host computer? Type "docker rm -f cocoa2025"            *
*                                                                         *
**************************************************************************

TF
echo -e "\e[0;33m"

if [[ $EUID -eq 0 ]]; then
  cat <<WARN
WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u \$(id -u):\$(id -g) args...
WARN
else
  cat <<EXPL
You are running this container as user with ID $(id -u) and group $(id -g),
which should map to the ID and group for your user on the Docker host. Great!
EXPL
fi

# Turn off colors
echo -e "\e[m"

# ------------------------------------------------------------------------
# Activate the cocoa conda environment
if [ -f "${CONDA_DIR:?}/etc/profile.d/conda.sh" ]; then
  source "${CONDA_DIR:?}/etc/profile.d/conda.sh"
  conda activate cocoa
fi
