--- makefile.orig	2025-09-03 17:34:17
+++ makefile	2025-09-03 18:21:43
@@ -33,12 +33,17 @@
 
 HEADERS = cuba$(SUFFIX).h
 LIB = libcuba$(SUFFIX).a
+UNAME_S := $(shell uname -s)
+ifeq ($(UNAME_S),Darwin)
+  LIBDYN = libcuba$(SUFFIX).dylib
+else
+  LIBDYN = libcuba$(SUFFIX).so
+endif
 MATH = Vegas$(SUFFIX)$(EXE) Suave$(SUFFIX)$(EXE) Divonne$(SUFFIX)$(EXE) Cuhre$(SUFFIX)$(EXE)
 TOOLS = partview$(EXE)
 
+all: lib $(LIBDYN)
 
-all: lib demos $(MATH_DEFAULT) $(TOOLS_DEFAULT)
-
 lib: $(LIB) $(HEADERS)
 
 demos: demo-c$(EXE) $(DEMO_FORTRAN_DEFAULT)
@@ -47,22 +52,29 @@
 
 tools: $(TOOLS)
 
+OBJS_U = \
+  Vegas_.o llVegas_.o Suave_.o llSuave_.o Divonne_.o llDivonne_.o \
+  Cuhre_.o llCuhre_.o Fork_.o Global_.o Data.o
 
-install: lib $(TOOLS_DEFAULT)
+$(LIBDYN): $(OBJS_U)
+	$(CC) -dynamiclib -o $@ $(OBJS_U) \
+	      -install_name @rpath/$(LIBDYN) \
+	      -Wl,-undefined,dynamic_lookup
+
+.PHONY: libdyn
+libdyn: $(LIBDYN)
+
+install: lib libdyn
 	$(INSTALL) -m 755 -d $(DESTDIR)$(libdir) \
 	                     $(DESTDIR)$(includedir) \
 	                     $(DESTDIR)$(bindir) \
 	                     $(DESTDIR)$(datadir)
 	$(INSTALL_DATA) $(LIB) $(DESTDIR)$(libdir)
+	$(INSTALL_DATA) $(LIBDYN) $(DESTDIR)$(libdir)
 	for f in $(HEADERS) ; do \
 	  $(INSTALL_DATA) `test -f $$f || echo $(srcdir)/`$$f $(DESTDIR)$(includedir); \
 	done
-	for f in $(MATH) $(TOOLS) ; do \
-	  test -f $$f && $(INSTALL_PROGRAM) $$f $(DESTDIR)$(bindir) || : ; \
-	done
-	$(INSTALL_DATA) $(srcdir)/cuba.pdf $(DESTDIR)$(datadir)
 
-
 check: demo-c
 	./demo-c | grep RESULT > demo-c.out
 	@echo diff demo-c.out $(demo)/demo-c.out
@@ -80,7 +92,6 @@
 demo = $(srcdir)/demo
 tools = $(srcdir)/tools
 
-
 COMMON_DEPS = $(common)/stddecl.h $(common)/ChiSquare.c $(common)/Erf.c
 COMMON_CDEPS = $(COMMON_DEPS) $(common)/CSample.c $(common)/Parallel.c $(common)/sock.h
 COMMON_TMDEPS = $(COMMON_DEPS) $(common)/MSample.c
@@ -94,39 +105,38 @@
   $(vegas)/Grid.c $(vegas)/Integrate.c
 VEGAS = $(VEGAS_C) $(VEGAS_TM) $(VEGAS_DEPS)
 
+Vegas.o: config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS) 
+	$(CC) $(CFLAGS) -fPIC -I$(vegas) -DNOUNDERSCORE -c -o Vegas.o $(VEGAS_C)
+
 $(LIB)(Vegas.o): config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS) 
 	$(CC) $(CFLAGS) -I$(vegas) -DNOUNDERSCORE -c -o Vegas.o $(VEGAS_C)
 	$(AR) $(ARFLAGS) $(LIB) Vegas.o
 	$(RM) Vegas.o
 
+llVegas.o: config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(vegas) -DLONGLONGINT -DNOUNDERSCORE -c -o llVegas.o $(VEGAS_C)
+
 $(LIB)(llVegas.o): config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(vegas) -DLONGLONGINT -DNOUNDERSCORE -c -o llVegas.o $(VEGAS_C)
 	$(AR) $(ARFLAGS) $(LIB) llVegas.o
 	$(RM) llVegas.o
 
+Vegas_.o: config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(vegas) -c -o Vegas_.o $(VEGAS_C)
+
 $(LIB)(Vegas_.o): config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(vegas) -c -o Vegas_.o $(VEGAS_C)
 	$(AR) $(ARFLAGS) $(LIB) Vegas_.o
 	$(RM) Vegas_.o
 
+llVegas_.o: config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(vegas) -DLONGLONGINT -c -o llVegas_.o $(VEGAS_C)
+
 $(LIB)(llVegas_.o): config.h $(VEGAS_C) $(VEGAS_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(vegas) -DLONGLONGINT -c -o llVegas_.o $(VEGAS_C)
 	$(AR) $(ARFLAGS) $(LIB) llVegas_.o
 	$(RM) llVegas_.o
 
-Vegas$(EXE): config.h $(VEGAS_TM) $(VEGAS_DEPS) $(COMMON_TMDEPS)
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(vegas) -o Vegas$(EXE) $(VEGAS_TM)
-	strip Vegas$(EXE)
-
-Vegasl$(EXE): config.h $(VEGAS_TM) $(VEGAS_DEPS) $(COMMON_TMDEPS)
-	sed '/:Begin:/,/:End:/ s/Real64/Real128/g' $(VEGAS_TM) > Vegasl.tm
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(vegas) -o Vegasl$(EXE) Vegasl.tm
-	strip Vegasl$(EXE)
-	$(RM) Vegasl.tm
-
-Vegasq$(EXE):
-
-
 SUAVE_C = $(suave)/Suave.c
 SUAVE_TM = $(suave)/Suave.tm
 SUAVE_DEPS = $(RNG_DEPS) \
@@ -135,39 +145,38 @@
   $(suave)/Integrate.c
 SUAVE = $(SUAVE_C) $(SUAVE_TM) $(SUAVE_DEPS)
 
+Suave.o: config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(suave) -DNOUNDERSCORE -c -o Suave.o $(SUAVE_C)
+
 $(LIB)(Suave.o): config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(suave) -DNOUNDERSCORE -c -o Suave.o $(SUAVE_C)
 	$(AR) $(ARFLAGS) $(LIB) Suave.o
 	$(RM) Suave.o
 
+llSuave.o: config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(suave) -DLONGLONGINT -DNOUNDERSCORE -c -o llSuave.o $(SUAVE_C)
+
 $(LIB)(llSuave.o): config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(suave) -DLONGLONGINT -DNOUNDERSCORE -c -o llSuave.o $(SUAVE_C)
 	$(AR) $(ARFLAGS) $(LIB) llSuave.o
 	$(RM) llSuave.o
 
+Suave_.o: config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(suave) -c -o Suave_.o $(SUAVE_C)
+
 $(LIB)(Suave_.o): config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(suave) -c -o Suave_.o $(SUAVE_C)
 	$(AR) $(ARFLAGS) $(LIB) Suave_.o
 	$(RM) Suave_.o
 
+llSuave_.o: config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(suave) -DLONGLONGINT -c -o llSuave_.o $(SUAVE_C)
+
 $(LIB)(llSuave_.o): config.h $(SUAVE_C) $(SUAVE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(suave) -DLONGLONGINT -c -o llSuave_.o $(SUAVE_C)
 	$(AR) $(ARFLAGS) $(LIB) llSuave_.o
 	$(RM) llSuave_.o
 
-Suave$(EXE): config.h $(SUAVE_TM) $(SUAVE_DEPS) $(COMMON_TMDEPS)
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(suave) -o Suave$(EXE) $(SUAVE_TM)
-	strip Suave$(EXE)
-
-Suavel$(EXE): config.h $(SUAVE_TM) $(SUAVE_DEPS) $(COMMON_TMDEPS)
-	sed '/:Begin:/,/:End:/ s/Real64/Real128/g' $(SUAVE_TM) > Suavel.tm
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(suave) -o Suavel$(EXE) Suavel.tm
-	strip Suavel$(EXE)
-	$(RM) Suavel.tm
-
-Suaveq$(EXE):
-
-
 DIVONNE_C = $(divonne)/Divonne.c
 DIVONNE_TM = $(divonne)/Divonne.tm
 DIVONNE_DEPS = $(RNG_DEPS) \
@@ -177,39 +186,38 @@
   $(divonne)/Split.c $(divonne)/Integrate.c
 DIVONNE = $(DIVONNE_C) $(DIVONNE_TM) $(DIVONNE_DEPS)
 
+Divonne.o: config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(divonne) -DNOUNDERSCORE -c -o Divonne.o $(DIVONNE_C)
+
 $(LIB)(Divonne.o): config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(divonne) -DNOUNDERSCORE -c -o Divonne.o $(DIVONNE_C)
 	$(AR) $(ARFLAGS) $(LIB) Divonne.o
 	$(RM) Divonne.o
 
+llDivonne.o: config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(divonne) -DLONGLONGINT -DNOUNDERSCORE -c -o llDivonne.o $(DIVONNE_C)
+
 $(LIB)(llDivonne.o): config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(divonne) -DLONGLONGINT -DNOUNDERSCORE -c -o llDivonne.o $(DIVONNE_C)
 	$(AR) $(ARFLAGS) $(LIB) llDivonne.o
 	$(RM) llDivonne.o
 
+Divonne_.o: config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(divonne) -c -o Divonne_.o $(DIVONNE_C)
+
 $(LIB)(Divonne_.o): config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(divonne) -c -o Divonne_.o $(DIVONNE_C)
 	$(AR) $(ARFLAGS) $(LIB) Divonne_.o
 	$(RM) Divonne_.o
 
+llDivonne_.o: config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(divonne) -DLONGLONGINT -c -o llDivonne_.o $(DIVONNE_C)
+
 $(LIB)(llDivonne_.o): config.h $(DIVONNE_C) $(DIVONNE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(divonne) -DLONGLONGINT -c -o llDivonne_.o $(DIVONNE_C)
 	$(AR) $(ARFLAGS) $(LIB) llDivonne_.o
 	$(RM) llDivonne_.o
 
-Divonne$(EXE): config.h $(DIVONNE_TM) $(DIVONNE_DEPS) $(COMMON_TMDEPS)
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(divonne) -o Divonne$(EXE) $(DIVONNE_TM)
-	strip Divonne$(EXE)
-
-Divonnel$(EXE): config.h $(DIVONNE_TM) $(DIVONNE_DEPS) $(COMMON_TMDEPS)
-	sed '/:Begin:/,/:End:/ s/Real64/Real128/g' $(DIVONNE_TM) > Divonnel.tm
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(divonne) -o Divonnel$(EXE) Divonnel.tm
-	strip Divonnel$(EXE)
-	$(RM) Divonnel.tm
-
-Divonneq$(EXE):
-
-
 CUHRE_C = $(cuhre)/Cuhre.c
 CUHRE_TM = $(cuhre)/Cuhre.tm
 CUHRE_DEPS = \
@@ -217,67 +225,78 @@
   $(cuhre)/Rule.c $(cuhre)/Integrate.c
 CUHRE = $(CUHRE_C) $(CUHRE_TM) $(CUHRE_DEPS)
 
+Cuhre.o: config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(cuhre) -DNOUNDERSCORE -c -o Cuhre.o $(CUHRE_C)
+
 $(LIB)(Cuhre.o): config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(cuhre) -DNOUNDERSCORE -c -o Cuhre.o $(CUHRE_C)
 	$(AR) $(ARFLAGS) $(LIB) Cuhre.o
 	$(RM) Cuhre.o
 
+llCuhre.o: config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(cuhre) -DLONGLONGINT -DNOUNDERSCORE -c -o llCuhre.o $(CUHRE_C)
+
 $(LIB)(llCuhre.o): config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(cuhre) -DLONGLONGINT -DNOUNDERSCORE -c -o llCuhre.o $(CUHRE_C)
 	$(AR) $(ARFLAGS) $(LIB) llCuhre.o
 	$(RM) llCuhre.o
 
+Cuhre_.o: config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(cuhre) -c -o Cuhre_.o $(CUHRE_C)
+
 $(LIB)(Cuhre_.o): config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(cuhre) -c -o Cuhre_.o $(CUHRE_C)
 	$(AR) $(ARFLAGS) $(LIB) Cuhre_.o
 	$(RM) Cuhre_.o
 
+llCuhre_.o: config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
+	$(CC) $(CFLAGS) -fPIC -I$(cuhre) -DLONGLONGINT -c -o llCuhre_.o $(CUHRE_C)
+
 $(LIB)(llCuhre_.o): config.h $(CUHRE_C) $(CUHRE_DEPS) $(COMMON_CDEPS)
 	$(CC) $(CFLAGS) -I$(cuhre) -DLONGLONGINT -c -o llCuhre_.o $(CUHRE_C)
 	$(AR) $(ARFLAGS) $(LIB) llCuhre_.o
 	$(RM) llCuhre_.o
 
-Cuhre$(EXE): config.h $(CUHRE_TM) $(CUHRE_DEPS) $(COMMON_TMDEPS)
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(cuhre) -o Cuhre$(EXE) $(CUHRE_TM)
-	strip Cuhre$(EXE)
+Fork.o: $(common)/Fork.c $(common)/stddecl.h $(common)/sock.h
+	$(CC) $(CFLAGS) -fPIC -DNOUNDERSCORE -c -o Fork.o $(common)/Fork.c
 
-Cuhrel$(EXE): config.h $(CUHRE_TM) $(CUHRE_DEPS) $(COMMON_TMDEPS)
-	sed '/:Begin:/,/:End:/ s/Real64/Real128/g' $(CUHRE_TM) > Cuhrel.tm
-	$(MCC) $(MCFLAGS) $(CFLAGS) -I$(cuhre) -o Cuhrel$(EXE) Cuhrel.tm
-	strip Cuhrel$(EXE)
-	$(RM) Cuhrel.tm
-
-Cuhreq$(EXE):
-
-
 $(LIB)(Fork.o): $(common)/Fork.c $(common)/stddecl.h $(common)/sock.h
 	$(CC) $(CFLAGS) -DNOUNDERSCORE -c -o Fork.o $(common)/Fork.c
 	$(AR) $(ARFLAGS) $(LIB) Fork.o
 	$(RM) Fork.o
 
+Fork_.o: $(common)/Fork.c $(common)/stddecl.h $(common)/sock.h
+	$(CC) $(CFLAGS) -fPIC -c -o Fork_.o $(common)/Fork.c
+
 $(LIB)(Fork_.o): $(common)/Fork.c $(common)/stddecl.h $(common)/sock.h
 	$(CC) $(CFLAGS) -c -o Fork_.o $(common)/Fork.c
 	$(AR) $(ARFLAGS) $(LIB) Fork_.o
 	$(RM) Fork_.o
 
+Global.o: $(common)/Global.c $(common)/stddecl.h
+	$(CC) $(CFLAGS) -fPIC -DNOUNDERSCORE -c -o Global.o $(common)/Global.c
 
 $(LIB)(Global.o): $(common)/Global.c $(common)/stddecl.h
 	$(CC) $(CFLAGS) -DNOUNDERSCORE -c -o Global.o $(common)/Global.c
 	$(AR) $(ARFLAGS) $(LIB) Global.o
 	$(RM) Global.o
 
+Global_.o: $(common)/Global.c $(common)/stddecl.h
+	$(CC) $(CFLAGS) -fPIC -c -o Global_.o $(common)/Global.c
+
 $(LIB)(Global_.o): $(common)/Global.c $(common)/stddecl.h
 	$(CC) $(CFLAGS) -c -o Global_.o $(common)/Global.c
 	$(AR) $(ARFLAGS) $(LIB) Global_.o
 	$(RM) Global_.o
 
+Data.o: $(common)/Data.c $(common)/stddecl.h
+	$(CC) $(CFLAGS) -fPIC -c -o Data.o $(common)/Data.c
 
 $(LIB)(Data.o): $(common)/Data.c $(common)/stddecl.h
 	$(CC) $(CFLAGS) -c -o Data.o $(common)/Data.c
 	$(AR) $(ARFLAGS) $(LIB) Data.o
 	$(RM) Data.o
 
-
 $(LIB): $(LIB)(Vegas.o)     $(LIB)(Vegas_.o)     \
 	$(LIB)(llVegas.o)   $(LIB)(llVegas_.o)   \
 	$(LIB)(Suave.o)     $(LIB)(Suave_.o)     \
@@ -291,71 +310,11 @@
 	$(LIB)(Data.o)
 	-$(RANLIB) $(LIB)
 
-
 cubal.h: cuba.h
 	sed 's/double/long double/g' cuba.h > cubal.h
 
 cubaq.h: cuba.h
 	sed 's/double/__float128/g' cuba.h > cubaq.h
 
-
-DEMO_F = $(demo)/demo-fortran.F
-DEMO_C = $(demo)/demo-c.c
-DEMO_TM = $(demo)/demo-math.m $(demo)/testsuite.m
-DEMO = $(DEMO_F) $(DEMO_C) $(DEMO_TM) $(demo)/demo-c.out $(demo)/cuba.F
-
-demo-fortran$(EXE): $(DEMO_F) lib
-	$(FC) $(FCFLAGS) -o demo-fortran$(EXE) $(DEMO_F) $(LIB) $(LIBS)
-
-demo-c$(EXE): $(DEMO_C) $(srcdir)/cuba.h lib
-	$(CC) $(CFLAGS) -o demo-c$(EXE) $(DEMO_C) $(LIB) $(LIBS)
-
-
-PARTVIEW = $(tools)/partview.cpp $(tools)/partview.pro \
-  $(tools)/quit.xpm $(tools)/print.xpm
-
-partview$(EXE): $(PARTVIEW)
-	qmake -o makefile.partview $(tools)/partview.pro
-	$(MAKE) -f makefile.partview
-	$(RM) partview.o partview.moc makefile.partview
-	-strip partview$(EXE)
-
-
-TARCONTENTS = $(srcdir)/COPYING $(srcdir)/ChangeLog \
-  $(srcdir)/configure $(srcdir)/configure.ac \
-  $(srcdir)/config.sub $(srcdir)/config.guess $(srcdir)/install-sh \
-  $(srcdir)/makefile.in $(srcdir)/config.h.in \
-  $(srcdir)/cuba.pdf $(srcdir)/cuba.tex $(srcdir)/cuba.h \
-  $(COMMON_CDEPS) $(COMMON_TMDEPS) $(common)/KorobovCoeff.c-* \
-  $(common)/Global.c $(common)/Fork.c $(common)/Data.c \
-  $(VEGAS) $(SUAVE) $(DIVONNE) $(CUHRE) \
-  $(DEMO) $(PARTVIEW) $(tools)/partview.m \
-  $(tools)/mcc $(tools)/fcc $(tools)/mkstatic $(tools)/mkdist.c
-
-dist:
-	mkdist cvfz $(TARFILE) $(TARDIR) \
-	  $(patsubst $(srcdir)/%,%, $(sort $(TARCONTENTS)))
-
-#	ln -s . $(TARDIR)
-#	tar cvfz $(TARFILE) --owner=root --group=root \
-#	  $(patsubst $(srcdir)/%,$(TARDIR)/%, $(sort $(TARCONTENTS)))
-#	$(RM) $(TARDIR)
-
-pub: dist
-	test -e web/cuba/$(TARFILE) && { \
-	  new=`date -r $(TARFILE) +%F`; \
-	  old=`date -r web/cuba/$(TARFILE) +%F`; \
-	  test $$new = $$old || mv -f web/cuba/$(TARDIR){,_$$old}.tar.gz; \
-	}; true
-	mv -f $(TARFILE) web/cuba/
-	./mkwebpage
-
 clean:
-	-$(RM) $(TARFILE) $(TARDIR) demo-c.out \
-	  partview.moc partview.o makefile.partview \
-	  cubal.h cubaq.h *.o */*.o */*.tm.c *.tm
-
-distclean: clean
-	-$(RM) $(LIB) demo-c demo-fortran $(MATH) $(TOOLS) \
-	  config.h config.log config.status makefile
-
+	-$(RM) cubal.h cubaq.h *.so *.a *.o */*.o */*.tm.c *.tm
