--- Makefile	2025-05-19 08:20:28.101080686 -0400
+++ Makefile2	2025-05-19 08:22:54.879019123 -0400
@@ -213,7 +213,7 @@
         site_packages=$$($(PYTHON) -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_lib())" || $(PYTHON) -c "import site; print(site.getsitepackages()[0])") && \
         echo "Cleaning up previous installation in: $$site_packages" && \
         rm -rf $$site_packages/classy* && \
-        $(PYTHON) -m pip install .; \
+        CC=$(CC) $(PYTHON) -m pip install . --user; \
     fi
 
 clean: .base
