--- Makefile	2024-06-13 12:11:33.457395725 -0400
+++ Makefile2	2024-06-13 12:13:23.711300236 -0400
@@ -22,17 +22,9 @@
 
 export MPI DEBUG
 
-# We can autodetect the compiler type on unix systems via the shell.
-# if you want to override this then just run make with
-# make COMPILER_TYPE=<your type>
-# where <your type> is gnu or intel
-ifeq "$(shell which ftn >/dev/null 2>&1; echo $$?)" "0"
-COMPILER_TYPE=cray
-else ifeq "$(shell which ifort >/dev/null 2>&1; echo $$?)" "0" 
-COMPILER_TYPE=intel
-else ifeq "$(shell which gfortran >/dev/null 2>&1; echo $$?)" "0"
+#VM BEGINS
 COMPILER_TYPE=gnu
-endif
+#VM ENDS
 
 ifeq ($(COMPILER_TYPE),intel)
 include Makefile_intel
