PROGRAM TEST

 USE BOPIX
 USE PARAMETER_MODULE
 USE LIBRARY

 IMPLICIT NONE
 
 REAL(4),ALLOCATABLE,DIMENSION(:,:) :: CL,CL_1, CHIMAT
 REAL(4),ALLOCATABLE,DIMENSION(:)   :: SINDEXVEC,AMPIVEC
 REAL(4)                            :: N_VALUE, A_VALUE, STEP, LOW_N, LOW_A, MENODUELOGLIK
 INTEGER(4)                         :: N_INDEX, A_INDEX, N_STEP, L_TILT, LMAX_INPUT
 INTEGER(4)                         :: K, L
 INTEGER(4)                         :: THIS_RECL
 REAL(8),PARAMETER             :: BOPIX_PI=3.14159265358979323846264338328D0

 N_STEP=100
 L_TILT=15
 LOW_A = 0.9D0
 LOW_N = 0.9D0
 STEP = 0.005D0
 LMAX_INPUT = 200
 
    ALLOCATE(CL(0:5,0:LMAX_INPUT))
    ALLOCATE(CL_1(0:5,0:LMAX_INPUT))
    ALLOCATE(SINDEXVEC(0:N_STEP-1))
    ALLOCATE(AMPIVEC(0:N_STEP-1))
    ALLOCATE(CHIMAT(0:N_STEP-1,0:N_STEP-1))
     
     CL   = 0.D0
     CL_1 = 0.D0
     
     OPEN(UNIT=1,FILE='INPUT/cl_t1.txt',STATUS='OLD',FORM='FORMATTED',ACTION='READ')
      DO L=2,200
        READ(1,*) K,CL_1(1,L), CL_1(2,L), CL_1(3,L), CL_1(4,L)
				CL_1(1,L)=CL_1(1,L)*2.D0*BOPIX_PI/L/(L+1)
				CL_1(2,L)=CL_1(2,L)*2.D0*BOPIX_PI/L/(L+1)
				CL_1(3,L)=CL_1(3,L)*2.D0*BOPIX_PI/L/(L+1)
				CL_1(4,L)=CL_1(4,L)*2.D0*BOPIX_PI/L/(L+1)
      END DO
     CLOSE(1)
			WRITE (*,*) "TT aa ",CL_1(2:5,1)
			WRITE (*,*) "EE aa ",CL_1(2:5,3)
			WRITE (*,*) "BB aa ",CL_1(2:5,4)
			WRITE (*,*) "TE aa ",CL_1(2:5,2)

    CALL BOPIX_PARAMETER_INIT
		CALL BOPIX_LIKELIHOOD(CL_1(0:200,:),MENODUELOGLIK)
		WRITE (*,*) MENODUELOGLIK
		END PROGRAM TEST
	  