unset -v FORTRAN_COMPILER C_COMPILER CXX_COMPILER MPI_FORTRAN_COMPILER
unset -v MPI_CXX_COMPILER MPI_CC_COMPILER AR_COMPILER RANLIB_COMPILER
unset -v DONT_USE_SYSTEM_PIP_PACKAGES
unset -v IGNORE_DISTUTILS_INSTALLATION IGNORE_ALL_PIP_INSTALLATION
unset -v IGNORE_OPENBLAS_INSTALLATION IGNORE_XZ_INSTALLATION
unset -v IGNORE_CMAKE_INSTALLATION IGNORE_CPP_INSTALLATION
unset -v IGNORE_CPP_CARMA_INSTALLATION IGNORE_CPP_BOOST_INSTALLATION
unset -v IGNORE_CPP_ARMA_INSTALLATION IGNORE_CPP_SPDLOG_INSTALLATION
unset -v IGNORE_C_INSTALLATION IGNORE_C_CFITSIO_INSTALLATION
unset -v IGNORE_C_FFTW_INSTALLATION IGNORE_C_GSL_INSTALLATION
unset -v IGNORE_FORTRAN_INSTALLATION IGNORE_CLASS_COMPILATION
unset -v IGNORE_CAMB_COMPILATION IGNORE_COSMOLIKE_COMPILATION
unset -v IGNORE_POLYCHORD_COMPILATION IGNORE_PLANCK_COMPILATION
unset -v GLOBAL_PACKAGES_LOCATION IGNORE_FORTRAN_LAPACK_INSTALLATION
unset -v IGNORE_ACTDR4_COMPILATION IGNORE_ACTDR6_COMPILATION
unset -v IGNORE_COBAYA_INSTALLATION PYSPD
unset -v IGNORE_LIPOP_INSTALLATION IGNORE_CAMSPEC_INSTALLATION
unset -v IGNORE_SO_INSTALLATION IGNORE_ALL_COBAYA_INSTALLATION
unset -v IGNORE_CPP_CUBA_INSTALLATION IGNORE_VELOCILEPTORS_COMPILATION
unset -v PYTHON_VERSION MANUAL_INSTALLATION MINICONDA_INSTALLATION
unset -v USE_SPT_CLIK_PLANCK DOCKER_INSTALLATION
unset -v CMAKE SET_INSTALLATION_OPTIONS IGNORE_HYREC_CODE
unset -v COSMOLIKE_DEBUG_MODE PYTHON_VERSION THREAD_UNXZ
unset -v MAKE_NUM_THREADS GLOBALPYTHON3 PIP3 PYTHON3 COBAYA_PACKAGES_PATH
unset -v GLOBAL_PACKAGES_INCLUDE COSMOLIKE_NDEBUG_COMMON_FLAGS
unset -v SPDLOG_LEVEL WGET GIT GLOBALPIP3 FFTW_NEW_VERSION POLY_URL
unset -v DEBUG_HDF5_PACKAGES DEBUG_DISTUTILS_PACKAGE DEBUG_UNXV_CLEAN_ALL
unset -v DEBUG_SIL_OUTPUT IGNORE_EMULATOR_PIP_PACKAGES IGNORE_ACT_COMPILATION
unset -v GLOBAL_PACKAGES_LIB MAKE_NB_JOBS IGNORE_HDF5_INSTALLATION
unset -v DEBUG_PLANCK_OUTPUT OUTPUT_PLANCK_1 OUTPUT_PLANCK_2 CFITSLIBS LAPALIBS
unset -v CMAKE_ROOT COCOA_OUTPUT_VERBOSE IGNORE_EMULATOR_GPU_PIP_PACKAGES
unset -v IGNORE_EMULATOR_CPU_PIP_PACKAGES COCOA_FFTW_DIR COCOA_HDF5_DIR1
unset -v COCOA_HDF5_DIR2 COCOA_CMAKE_DIR COCOA_CFITSIO_DIR COCOA_GSL_DIR
unset -v COCOA_TEXINFO_DIR COCOA_BINUTILS_DIR COCOA_LAPACK_DIR COCOA_SPDLOG_DIR
unset -v COCOA_ARMADILLO_DIR COCOA_CARMA_DIR COCOA_BOOST_DIR COCOA_EXPAT_DIR
unset -v COCOA_OPENBLAS_DIR COCOA_XZ_DIR COCOA_RUN_EVALUATE COCOA_RUN_MCMC
unset -v DEBUG_SKIP_FILE_DECOMPRESSION_COCOA COBAYA_PACKAGES_PATH
unset -v C_MAKE_NUM_THREADS FORTRAN_MAKE_NUM_THREADS MNT CMAKE_MAKE_NUM_THREADS
unset -v NO_UNXZ_COCOA_INSTALLATION_LIBRARIES
unset -v COBAYA COBAYA_COCOA CBLIKE CBTH HGL 
unset -v COBAYA_GIT_COMMIT HILLIPOP_GIT_COMMIT LOLLIPOP_GIT_COMMIT NERSC_WGET
unset -v LIPOP_DATA_VERSION CLIK_LAPALIBS CLIK_CFITSLIBS
unset -v SKIP_DECOMM_ACT SKIP_DECOMM_SPT SKIP_DECOMM_PLANCK SKIP_DECOMM_BICEP
unset -v SKIP_DECOMM_STRONG_LENSING SKIP_DECOMM_SN SKIP_DECOMM_BAO
unset -v SKIP_DECOMM_SIMONS_OBSERVATORY SKIP_DECOMM_CAMSPEC SKIP_DECOMM_LIPOP
unset -v GIT SPTURL HOLIURL PL2020_URL
unset -v PLK_DIR LPVS CAMSPEC_URL ACTDR6_LL PL_LWL BASECL PL2020 CBURL
unset -v POLY_NAME CAMB_NAME CAMB_GIT_COMMIT cocoa_HDF5_build
unset -v OUT1 OUT2 MNT URL CHANGES CLASS_NAME fail_sdf PACKDIR
unset -f pfail fail_comp_act fail_clact
unset -v INT_LIB INT_INCL INT_INCL_PY INT_INCL_PY_SP
unset -f ptop ptop2 ptop3 pbottom pbottom3 pbottom2
unset -v URL CHANGES ECODEF CLNAME PACKDIR TFOLDER TFILE TFILEP AL
unset -f cdfolder cpfolder error cpfile
unset -f unset_env_funcs unset_env_vars unset_all
unset -v EC1 EC2 EC3 EC4 EC5 EC6 EC7 EC8 EC9 EC10 EC11 EC12
unset -v EC13 EC14 EC15 EC16 EC17 EC18 EC19 EC20 EC21 EC22 EC23 EC24
unset -v EC25 EC26 EC27 EC28 EC29 EC30 EC31 EC32 EC33 EC34 EC35 EC36 EC37 EC38
unset -v EC39 EC40 EC41 EC42 EC43 EC44
unset -v HOLICOW_DATA_URL ACT_DR6_DATA_URL SPT3G_DATA_URL LIPOP_DATA_URL
unset -v HOLICOW_DATA_GIT_COMMIT SPT3G_DATA_GIT_COMMIT POLYCHORD_GIT_COMMIT
unset -v LOLLIPOP_URL HILLIPOP_URL COBAYA_URL COBAYA_GIT_COMMIT CAMB_URL 
unset -v VELOCILEPTORS_URL VELOCILEPTORS_GIT_COMMIT VELOCILEPTORS_NAME
unset -v SPT_3G_NAME ACT_NAME SO_DATA_URL SO_DATA_VERSION INT_INCL_PY_SP_NP
unset -v ACT_DR6_DATA_FILE ACT_DR6_DATA_URL ACTDR4_URL ACTDR4_GIT_COMMIT 
unset -v ACTDR4_NAME INT_INCL INT_LIB INT_INCL_PY INT_INCL_PY_SP 
unset -v ARMA_VERSION SPDLOG_VERSION GSL_VERSION FFTW_VERSION CFITSIO_VERSION
unset -v OPENBLAS_VERSION LAPACK_VERSION TEXTINFO_VERSION BINUTILS_VERSION
unset -v CMAKE_VERSION CPP_BOOST_VERSION CPP_CUBA_VERSION CLASS_URL
unset -v CLASS_GIT_COMMIT CLASS_NAME IGNORE_EXPAT_CORE_PACKAGE
unset -v IGNORE_PIP_CORE_PACKAGES IGNORE_WGET_INSTALLATION
unset -v IGNORE_SPT_CMB_DATA IGNORE_PLANCK_CMB_DATA IGNORE_MGCAMB_CODE
unset -v IGNORE_BICEP_CMB_DATA IGNORE_HOLICOW_STRONG_LENSING_DATA
unset -v IGNORE_SN_DATA IGNORE_BAO_DATA IGNORE_FGSPECTRA_CODE
unset -v IGNORE_SIMONS_OBSERVATORY_CMB_DATA IGNORE_CAMSPEC_CMB_DATA
unset -v IGNORE_LIPOP_CMB_DATA SCRIPTS IGNORE_EUCLID_EMULATOR_V2_CODE
unset -v IGNORE_CAMB_CODE IGNORE_CLASS_CODE IGNORE_ACTDR4_CODE 
unset -v IGNORE_COSMOLIKE_CODE IGNORE_POLYCHORD_SAMPLER_CODE
unset -v IGNORE_PLANCK_LIKELIHOOD_CODE IGNORE_ACTDR4_CODE
unset -v IGNORE_ACTDR6_CODE IGNORE_CPP_CUBA_INSTALLATION IGNORE_COBAYA_CODE
unset -v IGNORE_VELOCILEPTORS_CODE IGNORE_SIMONS_OBSERVATORY_LIKELIHOOD_CODE
unset -v IGNORE_CAMSPEC_LIKELIHOOD_CODE IGNORE_LIPOP_LIKELIHOOD_CODE 
unset -v IGNORE_COSMOREC_CODE